import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import {
  AspectRatio,
  Button,
  Card,
  Grid,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import Head from "next/head";
import Link from "next/link";
import classes from "../../styles/Index.module.css";
import Form from "@/components/Form";

const cardData = [
  {
    img: "/nove/Fotky_znacky_vozidel/Osobni_vozidla.webp",
    text: "Osobní vozidla",
    link: "/vozidla/osobni",
  },
  {
    img: "/nove/Fotky_znacky_vozidel/Nakladni_vozidla.webp",
    text: "Nákladní vozidla",
    link: "/vozidla/nakladni",
  },
  {
    img: "nove/Fotky_znacky_vozidel/Zemedelska_technika.webp",
    text: "Zemědělská a lesní technika",
    link: "/vozidla/agro",
  },
  {
    img: "nove/Fotky_znacky_vozidel/Stavebni_technika.webp",
    text: "Stavební technika",
    link: "/vozidla/bagry",
  },
  {
    img: "nove/Fotky_znacky_vozidel/Autobusy.webp",
    text: "Autobusy",
    link: "/vozidla/bus",
  },
  {
    img: "nove/Fotky_znacky_vozidel/Motorky.webp",
    text: "Motorky",
    link: "/vozidla/moto",
  },
  {
    img: "nove/Fotky_znacky_vozidel/Ctyrkolky.webp",
    text: "Čtyřkolky",
    link: "/vozidla/ctyrkolky",
  },
  {
    img: "nove/Fotky_znacky_vozidel/Lode.webp",
    text: "Lodě",
    link: "/vozidla/lode",
  },
];

const Vozidla = () => {
  const smallWindow = useMediaQuery("(max-width: 1200px)");

  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="TTC_WEB_Icon.svg" />
      </Head>
      <Navbar />
      <Hero
        image="/Foty_web_uvodni_hlavni_fotky/Znacky_vozidel_foto.webp"
        title="Vyhledejte sou značku vozidla a zjistěte na jaké parametry se lze dostat."
      />
      <Stack
        px={32}
        py={128}
        justify="center"
        align="center"
        gap={smallWindow ? 64 : 128}
        maw={1280}
        mx="auto"
        w="100%"
      >
        <Grid w="100%" gutter={smallWindow ? 24 : 64} mx="auto">
          {cardData.slice(0, 4).map((card, index) => (
            <Grid.Col span={{ base: 12, sm: 6 }} key={index}>
              <Link
                href={card.link}
                style={{ color: "inherit", textDecoration: "inherit" }}
              >
                <AspectRatio ratio={16 / 9}>
                  <Card
                    radius={16}
                    className={classes.card}
                    style={{
                      backgroundImage: `url("${card.img}")`,
                      backgroundPosition: "center",
                      backgroundRepeat: "no-repeat",
                      backgroundSize: "cover",
                      boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                      cursor: "pointer",
                    }}
                  >
                    <Stack h="100%" align="start" justify="end">
                      <Title
                        order={3}
                        c="white"
                        tt="uppercase"
                        pl={8}
                        fz={32}
                        maw="90%"
                      >
                        {card.text}
                      </Title>
                    </Stack>
                  </Card>
                </AspectRatio>
              </Link>
            </Grid.Col>
          ))}
        </Grid>

        <Card
          py="5vh"
          px={32}
          radius={0}
          style={{
            position: "relative",
            width: "100lvw",
            alignItems: "center",
            justifyContent: "center",
            gap: 24,
          }}
          c="white"
          bg="#101c24"
        >
          <Title
            order={3}
            fz={32}
            lh={1}
            style={{ scrollMarginTop: 100 }}
            ta="center"
          >
            Nevíte si rady a potřebujete poradit?
          </Title>
          <Text fz={20} ta="center">
            Kontaktujte nás na telefonním čísle{" "}
            <Link
              href="tel:+420 602 562 650"
              style={{
                color: "inherit",
                whiteSpace: "nowrap",
              }}
            >
              +420 602 562 650
            </Link>{" "}
            a nebo vyplňte jednoduchý formulář.
          </Text>
          <Link
            href="#form"
            style={{ color: "inherit", textDecoration: "inherit" }}
          >
            <Button
              color="#e84048"
              variant="filled"
              size="compact-xl"
              radius="md"
              px={32}
            >
              Kontaktujte nás
            </Button>
          </Link>
        </Card>

        <Grid w="100%" gutter={smallWindow ? 24 : 64} mx="auto">
          {cardData.slice(4, 8).map((card, index) => (
            <Grid.Col span={{ base: 12, sm: 6 }} key={index}>
              <Link
                href={card.link}
                style={{ color: "inherit", textDecoration: "inherit" }}
              >
                <AspectRatio ratio={16 / 9}>
                  <Card
                    radius={16}
                    className={classes.card}
                    style={{
                      backgroundImage: `url("${card.img}")`,
                      backgroundPosition: "center",
                      backgroundRepeat: "no-repeat",
                      backgroundSize: "cover",
                      boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                      cursor: "pointer",
                    }}
                  >
                    <Stack h="100%" align="start" justify="end">
                      <Title
                        order={3}
                        c="white"
                        tt="uppercase"
                        pl={8}
                        fz={32}
                        maw="90%"
                      >
                        {card.text}
                      </Title>
                    </Stack>
                  </Card>
                </AspectRatio>
              </Link>
            </Grid.Col>
          ))}
        </Grid>

        <Form />
      </Stack>
      <Footer />
    </>
  );
};

export default Vozidla;
