import Footer from "@/components/Footer";
import Form from "@/components/Form";
import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import {
  AspectRatio,
  Button,
  Card,
  Grid,
  List,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import classes from "../../styles/Index.module.css";

const cardData = [
  {
    heading: "MĚŘENÍ VÝKONU",
    subheading: "Osobní vozidla & Zemědělská technika",
    button: "Více informací",
    link: "/sluzby/zkusebna-vykonu",
    background: "./dlazdice/Fotky_dlazdice_2.webp",
  },
  {
    heading: "ZEMĚDĚLSKÁ TECHNIKA",
    subheading: "",
    button: "Více informací",
    link: "/sluzby/zemedelska-technika",
    background: "./dlazdice/Fotky_dlazdice_4.webp",
  },
  {
    heading: "NÁKLADNÍ VOZIDLA",
    subheading: "",
    button: "Více informací",
    link: "/sluzby/nakladni-vozidla",
    background: "./dlazdice/Fotky_dlazdice_6.webp",
  },
  {
    heading: "STAVEBNÍ TECHNIKA",
    subheading: "",
    button: "Více informací",
    link: "/sluzby/stavebni-technika",
    background: "./dlazdice/Fotky_dlazdice_3.webp",
  },
  {
    heading: "LESNÍ TECHNIKA",
    subheading: "",
    button: "Více informací",
    link: "/sluzby/lesni-technika",
    background: "./dlazdice/Fotky_dlazdice_5.webp",
  },
  {
    heading: "OSOBNÍ VOZIDLA",
    subheading: "",
    button: "Více informací",
    link: "/sluzby/osobni-vozidla",
    background: "./dlazdice/Fotky_dlazdice_1.webp",
  },
];

const Sluzby = () => {
  const router = useRouter();
  const smallWindow = useMediaQuery("(max-width: 1200px)");

  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="TTC_WEB_Icon.svg" />
      </Head>
      <Navbar />
      <Hero
        image="/Foty_web_uvodni_hlavni_fotky/Sluzby_foto.webp"
        title="Využijte náš široký sortiment služeb, které pro vás nabízíme."
        subText={
          <Text c="#e84048" fz={20}>
            Na co se specializujeme?
          </Text>
        }
      />
      <Stack
        px={32}
        py={128}
        justify="center"
        align="center"
        gap={smallWindow ? 64 : 128}
        maw={1280}
        mx="auto"
        w="100%"
      >
        <Stack gap={32} justify="center" w="100%">
          <Title order={3} fz={32} lh={1} style={{ scrollMarginTop: 100 }}>
            Nabízíme široký sortiment služeb
          </Title>
          <Text fz={20}>
            Naše společnost nabízí profesionální softwarové úpravy řídících
            jednotek motorů, emisních systémů a automatických převodovek.
          </Text>
          <Text fz={20}>
            Vlastní vývoj softwaru - Veškeré úpravy jsou vyvíjeny a testovány na
            zkušebně výkonu.
          </Text>
          <Text fz={20}>
            Kvalitní a bezpečné úpravy, díky spolupráci s nejlepšími na trhu:
            Dimsport, Autotuner, Alientech Bapro, Dynoproject, Remus výfukové
            systémy, DTE systémy a Eventuri karbonové sání a další ..
          </Text>
        </Stack>

        <Stack gap={32} justify="center" w="100%">
          <Title order={3} fz={32} lh={1} style={{ scrollMarginTop: 100 }}>
            Jsme mobilní po celé České republice
          </Title>
          <Text fz={20}>
            Platí pro nákladní vozidla, zemědělskou, lesní a stavební techniku.
          </Text>
          <Text fz={20}>
            Pro měření výkonu osobních vozidel je nutné dojet na válcovou
            zkušebnu výkonu na adresu Kotojedy 110, 767 01 Kroměříž - Kotojedy.
          </Text>
        </Stack>

        <Grid w="100%" gutter={smallWindow ? 24 : 64} mx="auto">
          {cardData.map((card, index) => (
            <Grid.Col span={{ base: 12, sm: 6 }} key={index}>
              <Link
                href={card.link}
                style={{ color: "inherit", textDecoration: "inherit" }}
              >
                <AspectRatio ratio={16 / 9}>
                  <Card
                    radius={16}
                    className={classes.card}
                    style={{
                      backgroundImage: `url("${card.background}")`,
                      backgroundPosition: "center",
                      backgroundRepeat: "no-repeat",
                      backgroundSize: "cover",
                      boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                      cursor: "pointer",
                    }}
                  >
                    <Stack h="100%" align="start" justify="end">
                      <Title order={3} c="white">
                        {card.heading}
                      </Title>
                      {card.subheading && (
                        <Text
                          c="white"
                          style={{
                            borderLeft: "1px solid white",
                            paddingLeft: 4,
                          }}
                        >
                          {card.subheading}
                        </Text>
                      )}
                      <Button
                        color="#e84048"
                        variant="filled"
                        size="compact-md"
                        radius="md"
                        px={32}
                        w="max-content"
                      >
                        {card.button}
                      </Button>
                    </Stack>
                  </Card>
                </AspectRatio>
              </Link>
            </Grid.Col>
          ))}
        </Grid>

        <Stack gap={32} justify="center" w="100%">
          <Title order={3} fz={32} lh={1} style={{ scrollMarginTop: 100 }}>
            Záruka na naše služby
          </Title>
          <List spacing={16}>
            <List.Item>
              <Text fz={20}>Záruka 14 dní na vrácení peněz.</Text>
            </List.Item>
            <List.Item>
              <Text fz={20}>
                Záruka 12 měsíců na řídící jednotku. (V případě mechanického
                zásahu do řídící jednotky).
              </Text>
            </List.Item>
            <List.Item>
              <Text fz={20}>Záruka 10 let na námi upravený software.</Text>
            </List.Item>
          </List>
        </Stack>

        <Text ta="center" fs="italic">
          Dle novely zákona č. 56/2001 Sb. o podmínkách provozu na pozemních
          komunikacích se vozidlo s neschválenou úpravou stává nezpůsobilé k
          provozu na pozemních komunikacích. Novela zákona, §83 odstavec 1,
          písmeno i) definuje podmínky takto: "fyzická osoba se dopustí
          přestupku tím, že jako provozovatel silničního vozidla v rozporu s §38
          odst. 1 písm. a) provozuje na pozemních komunikacích vozidlo, které je
          technicky nezpůsobilé k provozu."
        </Text>

        <Form />
      </Stack>

      <Footer />
    </>
  );
};

export default Sluzby;
