import Footer from "@/components/Footer";
import Form from "@/components/Form";
import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import {
  AspectRatio,
  Button,
  Card,
  Flex,
  Grid,
  List,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import classes from "../../styles/Index.module.css";
import Image from "next/image";

const cardData = [
  {
    img: "/nove/Fotky_zemedelska_technika/3_zemedelska_technika.webp",
  },
  {
    img: "/nove/Fotky_zemedelska_technika/1_zemedelska_technika.webp",
  },
  {
    img: "/nove/Fotky_zemedelska_technika/2_zemedelska_technika.webp",
  },
  {
    img: "/nove/Fotky_zemedelska_technika/4_zemedelska_technika.webp",
  },
];

const cards = [
  {
    title: "Chiptuning",
    description:
      "Využijte potenciál svého vozidla a maximalizujte pomocí optimalizace výkonu.",
    price: "Cena od 25 000,-",
  },
  {
    title: "Deaktivace systému SCR (AdBlue)",
    description: "Snižte své provozní náklady za opravy systému SCR (AdBlue).",
    price: "Cena od 25 000,-",
  },
  {
    title: "Deaktivace systému DPF",
    description:
      "Snižte své provozní náklady za opravy pomocí deaktivace systému DPF.",
    price: "Cena od 25 000,-",
  },
  {
    title: "Měření výkonu",
    description:
      "Mobilní dynamometr pro výkon motoru, měření točivého momentu.",
    price: "Cena od 8 000,-",
  },
  {
    title: "Deaktivace systému EGR",
    description: "Vyhnete se negativním vlivům, které systém EGR přináší.",
    price: "Cena od 18 000,-",
  },
  {
    title: "Diagnostika",
    description: "Podrobná diagnostika všech systémů vozidla.",
    price: "Cena od 2 000,-",
  },
];

const Sluzby = () => {
  const smallWindow = useMediaQuery("(max-width: 1200px)");

  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="TTC_WEB_Icon.svg" />
      </Head>
      <Navbar />
      <Hero
        image="/Foty_web_uvodni_hlavni_fotky/Sluzby_foto.webp"
        title="Využijte náš široký sortiment služeb, které pro vás nabízíme."
        subText={
          <Text c="#dc1735" fz={20}>
            Na co se specializujeme?
          </Text>
        }
      />
      <Stack
        px={32}
        py={128}
        justify="center"
        align="center"
        gap={smallWindow ? 64 : 128}
        maw={1280}
        mx="auto"
        w="100%"
      >
        <Grid w="100%" gutter={smallWindow ? 24 : 64}>
          <Grid.Col span={{ base: 12, sm: 6 }}>
            <AspectRatio
              ratio={4 / 3}
              style={{
                position: "relative",
                borderRadius: 16,
                boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
              }}
              h={smallWindow ? 360 : "100%"}
            >
              <Image
                quality={100}
                src="/nove/Fotky_zemedelska_technika/5_zemedelska_technika.webp"
                alt="/nove/Fotky_zemedelska_technika/5_zemedelska_technika.webp"
                fill
                sizes="100vw"
                style={{ borderRadius: 16 }}
              />
            </AspectRatio>
          </Grid.Col>
          <Grid.Col span={{ base: 12, sm: 6 }}>
            <Stack align="center" justify="center" w="100%" gap={64}>
              <Stack
                gap={16}
                justify="center"
                w="100%"
                py={smallWindow ? 0 : 128}
              >
                <Title
                  order={3}
                  fz={32}
                  lh={1}
                  style={{ scrollMarginTop: 100 }}
                >
                  S využitím naších služeb, Vaše zemědělská technika dosáhne
                  zcela jiných rozměrů!
                </Title>
              </Stack>
            </Stack>
          </Grid.Col>
        </Grid>

        <Stack gap={32} justify="center" w="100%">
          <Title
            order={3}
            fz={32}
            lh={1}
            style={{ scrollMarginTop: 100 }}
            ta="center"
          >
            Oblíbené služby našich zákazníků
          </Title>

          <Grid w="100%" gutter={32} maw={1280} mx="auto">
            {cards.map((card, index) => (
              <Grid.Col span={{ lg: 4, md: 6, sm: 12 }} key={index}>
                <AspectRatio ratio={1 / 1}>
                  <Card
                    className={classes.card}
                    radius={16}
                    style={{
                      boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                      justifyContent: "center",
                    }}
                    p={32}
                  >
                    <Stack align="center" justify="center" h="100%">
                      <Text fz={24} fw={700} ta="center">
                        {card.title}
                      </Text>
                      <Text fz={20} ta="center">
                        {card.description}
                      </Text>
                      <Text c="#dc1735" fz={20} ta="center">
                        {card.price}
                      </Text>
                    </Stack>
                  </Card>
                </AspectRatio>
              </Grid.Col>
            ))}
          </Grid>
          <Flex align="center" justify="center" mx="auto" gap={16} wrap="wrap">
            <Link
              href="#form"
              style={{ color: "inherit", textDecoration: "inherit" }}
            >
              <Button
                color="#dc1735"
                variant="filled"
                size="compact-xl"
                radius="lg"
                px={32}
                w={256}
              >
                Kontaktujte nás
              </Button>
            </Link>
            <Link
              href="/sluzby"
              style={{ color: "inherit", textDecoration: "inherit" }}
            >
              <Button
                color="#dc1735"
                variant="filled"
                size="compact-xl"
                radius="lg"
                px={32}
                w={256}
              >
                Více služeb
              </Button>
            </Link>
          </Flex>
        </Stack>

        <Card
          py="5vh"
          px={32}
          radius={0}
          style={{
            position: "relative",
            width: "100lvw",
            alignItems: "center",
            justifyContent: "center",
            gap: 24,
          }}
          c="white"
          bg="#101c24"
        >
          <Title order={3} fz={32} lh={1} style={{ scrollMarginTop: 100 }}>
            Parametry výkonu
          </Title>
          <Text fz={20} ta="center">
            Zjisti více informací o možném navýšení výkonu svého vozidla.
          </Text>
          <Link
            href="/vozidla"
            style={{ color: "inherit", textDecoration: "inherit" }}
          >
            <Button
              color="#dc1735"
              variant="filled"
              size="compact-xl"
              radius="lg"
              px={32}
            >
              Značky vozidel
            </Button>
          </Link>
        </Card>

        <Stack gap={32} justify="center" w="100%">
          <Title order={3} fz={32} lh={1} style={{ scrollMarginTop: 100 }}>
            Zdarma 30 dní zkušební lhůta
          </Title>

          <Text fz={20}>
            Nabízíme zdarma 30 dní zkušební lhůtu na námi provedenou
            optimalizaci výkonu.
          </Text>

          <Grid w="100%" gutter={smallWindow ? 24 : 64} mx="auto" mt={16}>
            {cardData.map((card, index) => (
              <Grid.Col span={{ base: 12, sm: 6 }} key={index}>
                <AspectRatio ratio={16 / 9}>
                  <Card
                    radius={16}
                    style={{
                      backgroundImage: `url("${card.img}")`,
                      backgroundPosition: "center",
                      backgroundRepeat: "no-repeat",
                      backgroundSize: "cover",
                      boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                    }}
                  />
                </AspectRatio>
              </Grid.Col>
            ))}
          </Grid>
        </Stack>

        <Form />
      </Stack>

      <Footer />
    </>
  );
};

export default Sluzby;
