import Footer from "@/components/Footer";
import Form from "@/components/Form";
import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import {
  AspectRatio,
  Button,
  Card,
  Grid,
  List,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import classes from "../../styles/Index.module.css";
import Image from "next/image";

const cardData = [
  {
    img: "/nove/Fotky_mereni_vykonu/4_mereni_vykonu.webp",
  },
  {
    img: "/nove/Fotky_mereni_vykonu/2_mereni_vykonu.webp",
  },
  {
    img: "/nove/Fotky_mereni_vykonu/3_mereni_vykonu.webp",
  },
  {
    img: "/nove/Fotky_mereni_vykonu/1_mereni_vykonu.webp",
  },
];

const Sluzby = () => {
  const smallWindow = useMediaQuery("(max-width: 1200px)");

  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/media/Premium Package/Logos (Vector Format)/Transparent.svg"
        />
      </Head>
      <Navbar />
      <Hero
        image="/Foty_web_uvodni_hlavni_fotky/Sluzby_foto.webp"
        title="Využijte náš široký sortiment služeb, které pro vás nabízíme."
        subText={
          <Text c="#e84048" fz={20}>
            Na co se specializujeme?
          </Text>
        }
      />
      <Stack
        px={32}
        py={128}
        justify="center"
        align="center"
        gap={smallWindow ? 64 : 128}
        maw={1280}
        mx="auto"
        w="100%"
      >
        <Stack gap={32} justify="center" w="100%">
          <Title order={3} fz={32} lh={1} style={{ scrollMarginTop: 100 }}>
            4x4 Válcová zkušebna výkonu
          </Title>
          <Text fz={20}>
            Řada HP je nejvýkonnějším podvozkovým dynamometrem Bapro. Čtyři
            všechny spojené válce o průměru 400 mm na každou nápravu zaručují
            špičkovou opakovatelnost a přesnost.
          </Text>
          <Text fz={20}>
            Elektronicky propojené a synchronizované nápravy prostřednictvím
            softwaru, vytvořené rychlým a přesným vysokofrekvenčním řízením brzd
            s vířivými proudy, s cílem synchronizovat nápravy ve voze 4wd
            (patentovaný systém Bapro).
          </Text>
          <Text fz={20}>
            Tato funkce zabraňuje jakémukoli poškození diferenciálů a pomáhá
            provádět přesnější testy, protože je také zabráněno plýtvání výkonem
            kvůli prokluzování uvnitř diferenciálů.
          </Text>

          <Grid w="100%" gutter={smallWindow ? 24 : 64} mt={16}>
            <Grid.Col span={{ base: 12, sm: 6 }}>
              <AspectRatio
                ratio={4 / 3}
                style={{
                  position: "relative",
                  borderRadius: 16,
                  boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                }}
                h={smallWindow ? 360 : "100%"}
              >
                <Image
                  quality={100}
                  src="/nove/Fotky_mereni_vykonu/5_mereni_vykonu.webp"
                  alt="/nove/Fotky_mereni_vykonu/5_mereni_vykonu.webp"
                  fill
                  sizes="100vw"
                  style={{ borderRadius: 16 }}
                />
              </AspectRatio>
            </Grid.Col>
            <Grid.Col span={{ base: 12, sm: 6 }}>
              <Stack align="center" justify="center" w="100%" gap={64}>
                <Stack
                  gap={16}
                  justify="center"
                  w="100%"
                  py={smallWindow ? 0 : 64}
                >
                  <Title
                    order={3}
                    fz={32}
                    lh={1}
                    style={{ scrollMarginTop: 100 }}
                  >
                    Základní informace
                  </Title>
                  <List spacing={16}>
                    <List.Item>
                      <Text fz={20}>Maximální rychlost 360 km/h</Text>
                    </List.Item>
                    <List.Item>
                      <Text fz={20}>Maximální měřitelný výkon 2 000 HP</Text>
                    </List.Item>
                    <List.Item>
                      <Text fz={20}>
                        Maximální absorbovatelný výkon 1 300 HP
                      </Text>
                    </List.Item>
                    <List.Item>
                      <Text fz={20}>Maximální tažná síla 3 200 Nm</Text>
                    </List.Item>
                  </List>
                </Stack>
              </Stack>
            </Grid.Col>
          </Grid>
        </Stack>

        <Stack gap={32} justify="center" w="100%">
          <Title order={3} fz={32} lh={1} style={{ scrollMarginTop: 100 }}>
            AGRO DYNO - Měření výkonu
          </Title>
          <Text fz={20}>
            Mobilní dynamometr pro měření výkonu traktorů přes vývodový hřídel
            PTO. Maximální měřitelný výkon je do 450 Hp a 2 000 Nm.
          </Text>
          <Grid w="100%" gutter={smallWindow ? 24 : 64} mt={16}>
            <Grid.Col span={{ base: 12, sm: 6 }}>
              <AspectRatio
                ratio={4 / 3}
                style={{
                  position: "relative",
                  borderRadius: 16,
                  boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                }}
                h={smallWindow ? 360 : "100%"}
              >
                <Image
                  quality={100}
                  src="/nove/Fotky_mereni_vykonu/2_mereni_vykonu.webp"
                  alt="/nove/Fotky_mereni_vykonu/2_mereni_vykonu.webp"
                  fill
                  sizes="100vw"
                  style={{ borderRadius: 16 }}
                />
              </AspectRatio>
            </Grid.Col>
            <Grid.Col span={{ base: 12, sm: 6 }}>
              <Stack
                gap={16}
                justify="center"
                w="100%"
                py={smallWindow ? 0 : 64}
              >
                <Title
                  order={3}
                  fz={32}
                  lh={1}
                  style={{ scrollMarginTop: 100 }}
                >
                  Zkušební lhůta
                </Title>
                <Text fz={20}>
                  Zdarma 30 dní zkušební lhůta, na námi provedenou optimalizaci
                  výkonu.
                </Text>
                <Link
                  href="#form"
                  style={{ color: "inherit", textDecoration: "inherit" }}
                >
                  <Button
                    color="#e84048"
                    variant="filled"
                    size="compact-xl"
                    radius="md"
                    px={32}
                  >
                    Kontaktujte nás
                  </Button>
                </Link>
              </Stack>
            </Grid.Col>
          </Grid>
        </Stack>

        <Card
          py="5vh"
          px={32}
          radius={0}
          style={{
            position: "relative",
            width: "100lvw",
            alignItems: "center",
            justifyContent: "center",
            gap: 24,
          }}
          c="white"
          bg="#101c24"
        >
          <Title order={3} fz={32} lh={1} style={{ scrollMarginTop: 100 }}>
            Parametry výkonu
          </Title>
          <Text fz={20} ta="center">
            Zjisti více informací o možném navýšení výkonu svého vozidla.
          </Text>
          <Link
            href="/vozidla"
            style={{ color: "inherit", textDecoration: "inherit" }}
          >
            <Button
              color="#e84048"
              variant="filled"
              size="compact-xl"
              radius="md"
              px={32}
            >
              Značky vozidel
            </Button>
          </Link>
        </Card>

        <Stack gap={32} justify="center" w="100%">
          <Title order={3} fz={32} lh={1} style={{ scrollMarginTop: 100 }}>
            Pronájem zkušebny
          </Title>
          <List spacing={16}>
            <List.Item>
              <Text fz={20}>
                Možnost pronájmu zkušebny pro své vlastní účely.
              </Text>
            </List.Item>
            <List.Item>
              <Text fz={20}>
                Cena pronájmu je od 2 699 Kč na hodinu bez DPH.
              </Text>
            </List.Item>
            <List.Item>
              <Text fz={20}>
                Po celou dobu s technikem, který zkušebnu bude obsluhovat.
              </Text>
            </List.Item>
          </List>

          <Grid w="100%" gutter={smallWindow ? 24 : 64} mx="auto" mt={16}>
            {cardData.map((card, index) => (
              <Grid.Col span={{ base: 12, sm: 6 }} key={index}>
                <AspectRatio ratio={16 / 9}>
                  <Card
                    radius={16}
                    style={{
                      backgroundImage: `url("${card.img}")`,
                      backgroundPosition: "center",
                      backgroundRepeat: "no-repeat",
                      backgroundSize: "cover",
                      boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                    }}
                  />
                </AspectRatio>
              </Grid.Col>
            ))}
          </Grid>
        </Stack>

        <Form />
      </Stack>

      <Footer />
    </>
  );
};

export default Sluzby;
