import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styled from "styled-components";

const StyledDetail = styled.main`
  background-image: url("../../bg.svg");
  background-size: cover;
  background-position: top;
  padding: 8rem 0;

  width: 100%;
  height: auto;
  min-height: 100vh;

  color: #101c24;
`;

const Detail = () => {
  const router = useRouter();
  const { name, detail } = router.query;
  const [loaded, setLoaded] = useState(false);
  const [params, setParams] = useState({});

  async function fetchModels() {
    const res = await fetch(
      `/api/detail?` +
        new URLSearchParams({
          detail: "https://www.dynocheck.com/cs/catalog/detail/" + detail,
        })
    );
    const json = await res.json();
    setParams(json[0]);
    setLoaded(true);
  }

  useEffect(() => {
    fetchModels();
  }, [detail]);

  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/media/Premium Package/Logos (Vector Format)/Transparent.svg"
        />
      </Head>
      <Navbar />

      <StyledDetail>
        <h1>{name}</h1>
        <p>{params && params.original}</p>
        <p>{params && params.maximal}</p>
      </StyledDetail>

      <Footer />
    </>
  );
};

export default Detail;
