import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

const StyledRealizace = styled.main`
  background-image: url("../../bg.svg");
  background-size: cover;
  background-position: top;

  width: 100%;
  height: auto;

  color: #101c24;

  .hero {
    margin-bottom: 4rem;
    width: 100vw;
    height: 50vh;

    background-image: url("./media/foto/vozidla.webp");
    background-size: cover;
    background-position: center;

    display: flex;
    align-content: center;
    justify-content: center;

    color: white;

    div {
      align-self: center;
      text-align: center;

      h1 {
        font-size: 4rem;
        font-weight: bolder;
        line-height: 4.75rem;

        @media (max-width: 1280px) {
          font-size: 3rem;
        }
        @media (max-width: 600px) {
          font-size: 2rem;
        }
      }
      p {
        font-size: 2rem;
        font-weight: 100;

        @media (max-width: 1280px) {
          font-size: 1.5rem;
          letter-spacing: 0;
        }
        @media (max-width: 600px) {
          font-size: 1.5rem;
        }
      }
    }
  }

  .container {
    width: 75vw;
    margin: 0 auto 3rem auto;
    display: flex;
    flex-direction: row;
    justify-content: center;
    @media (max-width: 1280px) {
      flex-wrap: wrap;
      gap: 3rem;
    }
    gap: 3rem;

    a {
      text-decoration: none !important;
    }

    .card {
      width: 8rem;
      height: 9rem;
      padding: 1rem;
      font-size: 0.75rem;

      -webkit-box-shadow: -16px 16px 0px 0px #c3c7ca89;
      -moz-box-shadow: -16px 16px 0px 0px #c3c7ca89;
      box-shadow: -16px 16px 0px 0px #c3c7ca89;

      display: flex;
      flex-direction: column;

      border-radius: 2rem;
      background-color: #101c24;
      color: white;
      text-align: center;

      text-decoration: none !important;

      p {
        margin-top: auto;
        text-decoration: none !important;
      }

      img {
        padding: 1rem;
      }
      svg {
        padding: 1.5rem;
      }
    }
  }
`;

const Vozidla = () => {
  const handleSearch = async () => {
    fetch(
      `/api/carModels?link=https://www.dynocheck.com/cs/catalog/detail/ducati-748-71kw`
    )
      .then((res) => res.json())
      .then((data) => console.log(data))
      .catch((err) => console.error(err));
  };

  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/media/Premium Package/Logos (Vector Format)/Transparent.svg"
        />
      </Head>
      <Navbar />
      <StyledRealizace>
        <div className="hero">
          <div>
            <h1 onClick={() => handleSearch()}>ZNAČKY VOZIDEL</h1>
          </div>
        </div>
        <div className="container">
          <Link href="/vozidla/osobni">
            <div className="card">
              <p>Osobní vozidla</p>
              <img src="./media/icons/car.png" alt="" />
            </div>
          </Link>
          <Link href="/vozidla/nakladni">
            <div className="card">
              <p>Nákladní vozidla</p>
              <img src="./media/icons/iconmonstr-delivery-1.svg" alt="" />
            </div>
          </Link>
          <Link href="/vozidla/agro">
            <div className="card">
              <p>Zemědělská a lesní technika</p>
              <img
                src="./media/icons/tractor-agriculture-torque-construction-equipment-svgrepo-com.svg"
                alt=""
              />
            </div>
          </Link>
          <Link href="/vozidla/bagry">
            <div className="card">
              <p>Stavební technika</p>
              <img src="./media/icons/iconmonstr-construction-4.svg" alt="" />
            </div>
          </Link>
          <Link href="/vozidla/bus">
            <div className="card">
              <p>Autobusy</p>
              <img src="./media/icons/iconmonstr-bus-5.svg" alt="" />
            </div>
          </Link>
        </div>

        <div className="container">
          <Link href="/vozidla/moto">
            <div className="card">
              <p>Motorky</p>
              <img src="./media/icons/motorcycle-f-svgrepo-com.svg" alt="" />
            </div>
          </Link>
          <Link href="/vozidla/ctyrkolky">
            <div className="card">
              <p>Čtyřkolky</p>
              <img src="./media/icons/quad-bike-2-svgrepo-com.svg" alt="" />
            </div>
          </Link>
          <Link href="/vozidla/lod">
            <div className="card">
              <p>Lodě</p>
              <img
                src="./media/icons/ship-boat-svgrepo-com.svg"
                alt=""
                style={{ transform: "scaleX(-1)" }}
              />
            </div>
          </Link>
        </div>
        <p>&#8203;</p>
      </StyledRealizace>
      <Footer />
    </>
  );
};

export default Vozidla;
