import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

const StyledRealizace = styled.main`
  background-image: url("../../bg.svg");
  background-size: cover;
  background-position: top;

  width: 100%;
  height: auto;
  min-height: 100vh;

  color: #101c24;

  h1 {
    font-size: 5rem;
    letter-spacing: -4px;
    font-weight: 900;
    text-align: center;
    margin: 8rem 0;
  }

  .container {
    width: 75vw;
    margin: 0 auto 6rem auto;
    display: flex;
    flex-direction: row;
    justify-content: center;
    @media (max-width: 1280px) {
      flex-wrap: wrap;
      gap: 6rem;
    }
    gap: 12rem;

    a {
      text-decoration: none !important;
    }

    .card {
      width: 12rem;
      height: 14rem;
      padding: 1rem;

      display: flex;
      flex-direction: column;

      border-radius: 2rem;
      background-color: #101c24;
      color: white;
      font-size: 1.55rem;
      text-align: center;

      text-decoration: none !important;

      p {
        margin-top: auto;
        text-decoration: none !important;
      }

      img {
        padding: 2.5rem;
        padding-top: 1.5rem;
      }
      svg {
        padding: 1.5rem;
      }
    }
  }
`;

const Vozidla = () => {
  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/media/Premium Package/Logos (Vector Format)/Transparent.svg"
        />
      </Head>
      <Navbar />
      <StyledRealizace>
        <img src="./media/foto/realizace.png" alt="" />
        <h1>Značky vozidel</h1>
        <div className="container">
          <Link href="/vozidla/osobni">
            <div className="card">
              <p>Osobní vozidla</p>
              <img src="./media/icons/car.png" alt="" />
            </div>
          </Link>
          <Link href="/vozidla/nakladni">
            <div className="card">
              <p>Nákladní vozidla</p>
              <img src="./media/icons/iconmonstr-delivery-1.svg" alt="" />
            </div>
          </Link>
          <Link href="/vozidla/agro">
            <div className="card">
              <p>Agro vozidla</p>
              <img
                src="./media/icons/tractor-agriculture-torque-construction-equipment-svgrepo-com.svg"
                alt=""
              />
            </div>
          </Link>
          <Link href="/vozidla/bus">
            <div className="card">
              <p>Autobusová vozidla</p>
              <img src="./media/icons/iconmonstr-bus-5.svg" alt="" />
            </div>
          </Link>
        </div>

        <div className="container">
          <Link href="/vozidla/ctyrkolky">
            <div className="card">
              <p>Čtyřkolky</p>
              <img src="./media/icons/quad-bike-2-svgrepo-com.svg" alt="" />
            </div>
          </Link>
          <Link href="/vozidla/lod">
            <div className="card">
              <p>Lodě</p>
              <img src="./media/icons/ship-boat-svgrepo-com.svg" alt="" />
            </div>
          </Link>
          <Link href="/vozidla/bagry">
            <div className="card">
              <p>Bagry a stroje</p>
              <img src="./media/icons/iconmonstr-construction-4.svg" alt="" />
            </div>
          </Link>
        </div>
        <p>&#8203;</p>
      </StyledRealizace>
      <Footer />
    </>
  );
};

export default Vozidla;
