import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import styled from "styled-components";

const StyledRealizace = styled.main`
  background-image: url("./bg.svg");
  background-size: cover;
  background-position: top;

  width: 100%;
  height: auto;
  min-height: 100vh;

  color: #101c24;

  h1 {
    font-size: 5rem;
    letter-spacing: -4px;
    font-weight: 900;
    text-align: center;
    margin: 8rem 0;
  }
`;

const Vozidla = () => {
  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/media/Premium Package/Logos (Vector Format)/Transparent.svg"
        />
      </Head>
      <Navbar />
      <StyledRealizace>
        <img src="./media/foto/realizace.png" alt="" />
        <h1>Bagry</h1>

        <p>&#8203;</p>
      </StyledRealizace>
      <Footer />
    </>
  );
};

export default Vozidla;
