import Footer from "@/components/Footer";
import Form from "@/components/Form";
import Hero from "@/components/Hero";
import MoreInfo from "@/components/MoreInfo";
import Navbar from "@/components/Navbar";
import { Button, Card, Flex, Stack, Text, Title } from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import Head from "next/head";
import Link from "next/link";
import styles from "./cenik.module.css";

const Cenik = () => {
  const smallWindow = useMediaQuery("(max-width: 1200px)");

  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="TTC_WEB_Icon.svg" />
      </Head>
      <Navbar />
      <Hero
        image="/Foty_web_uvodni_hlavni_fotky/Sluzby_foto.webp"
        title="Jsme féroví! Naše ceny optimalizujeme tak, aby byly výhodné pro obě strany."
        subText={
          <Text c="#dc1735" fz={20}>
            Nejlepší ceny na trhu!
          </Text>
        }
      />
      <Stack
        px={32}
        py={128}
        justify="center"
        align="center"
        gap={smallWindow ? 64 : 128}
        maw={1280}
        mx="auto"
        w="100%"
      >
        <Stack gap={8} w="100%" align="center">
          <div className={styles.header}>
            <h2>Osobní a užitková vozidla</h2>
          </div>
          <div className={styles.table}>
            <table>
              <tbody>
                <tr>
                  <td>Chiptuning s měřením výkonu</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 5 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Oprava systému AdBlue/DPF</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 5 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Programování AUT převodovek</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 5 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Odstranění funkce EGR</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 3 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Omezovače otáček</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 3 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Omezovače rychlosti</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 3 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Měření výkonu na brzdě 4x4</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 3 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Diagnostika (paralelní/sériová)</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 800 Kč
                  </td>
                </tr>
                <tr>
                  <td style={{ border: "none" }}></td>
                  <td
                    style={{
                      border: "none",
                      borderLeft: "2px solid #0b1e25",
                      whiteSpace: "nowrap",
                    }}
                  ></td>
                </tr>
              </tbody>
            </table>
            <p style={{ fontStyle: "italic", fontSize: 14 }}>
              *Veškeré uvedené ceny jsou bez DPH.
            </p>
          </div>
        </Stack>

        <Stack gap={8} w="100%" align="center">
          <div className={styles.header}>
            <h2>Nákladní vozidla a autobusy</h2>
          </div>
          <div className={styles.table}>
            <table>
              <tbody>
                <tr>
                  <td>Chiptuning</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 25 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Chip truck</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 25 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Deaktivace systému AdBlue/DPF truck/bus</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 25 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Deaktivace EGR ventilu</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 18 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Snížení dávky vstřikování AdBlue</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 22 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Odstranění nouzového režimu</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 15 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Odstranění nouzového režimu E6</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 20 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Vyjezd mobilního technika</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 3 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Diagnostika</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 1 500 Kč
                  </td>
                </tr>
                <tr>
                  <td style={{ border: "none" }}></td>
                  <td
                    style={{
                      border: "none",
                      borderLeft: "2px solid #0b1e25",
                      whiteSpace: "nowrap",
                    }}
                  ></td>
                </tr>
              </tbody>
            </table>
            <p style={{ fontStyle: "italic", fontSize: 14 }}>
              *Veškeré uvedené ceny jsou bez DPH.
            </p>
          </div>
        </Stack>

        <Stack gap={8} w="100%" align="center">
          <div className={styles.header}>
            <h2>Zemědělská technika</h2>
          </div>
          <div className={styles.table}>
            <table>
              <tbody>
                <tr>
                  <td>Chiptuning agro</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 25 000 Kč
                  </td>
                </tr>
                <tr>
                  <td>Deaktivace AdBlue/DPF agro</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 25 000 Kč (dle výrobce motoru/ECU)
                  </td>
                </tr>
                <tr>
                  <td>Diagnostika</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 2 000 Kč
                  </td>
                </tr>
                <tr>
                  <td style={{ border: "none" }}></td>
                  <td
                    style={{
                      border: "none",
                      borderLeft: "2px solid #0b1e25",
                      whiteSpace: "nowrap",
                    }}
                  ></td>
                </tr>
              </tbody>
            </table>
            <p style={{ fontStyle: "italic", fontSize: 14 }}>
              *Veškeré uvedené ceny jsou bez DPH.
            </p>
          </div>
        </Stack>

        <Stack gap={8} w="100%" align="center">
          <div className={styles.header}>
            <h2>Stavební a lesní technika</h2>
          </div>
          <div className={styles.table}>
            <table>
              <tbody>
                <tr>
                  <td>Chiptuning stavební/lesní</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 25 000 Kč (dle výrobce motoru/ECU)
                  </td>
                </tr>
                <tr>
                  <td>Deaktivace AdBlue/DPF stavební/lesní</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 25 000 Kč (dle výrobce motoru/ECU)
                  </td>
                </tr>
                <tr>
                  <td>Diagnostika</td>
                  <td
                    style={{
                      width: "12rem",
                      borderLeft: "2px solid #0b1e25",
                    }}
                  >
                    od 2 000 Kč
                  </td>
                </tr>
                <tr>
                  <td style={{ border: "none" }}></td>
                  <td
                    style={{
                      border: "none",
                      borderLeft: "2px solid #0b1e25",
                      whiteSpace: "nowrap",
                    }}
                  ></td>
                </tr>
              </tbody>
            </table>
            <p style={{ fontStyle: "italic", fontSize: 14 }}>
              *Veškeré uvedené ceny jsou bez DPH.
            </p>
          </div>
        </Stack>

        <Flex align="center" justify="center" mx="auto" gap={16} wrap="wrap">
          <Link
            href="#form"
            style={{ color: "inherit", textDecoration: "inherit" }}
          >
            <Button
              color="#dc1735"
              variant="filled"
              size="compact-xl"
              radius="lg"
              px={32}
              w={256}
            >
              Kontaktujte nás
            </Button>
          </Link>
          <Link
            href="/sluzby"
            style={{ color: "inherit", textDecoration: "inherit" }}
          >
            <Button
              color="#dc1735"
              variant="filled"
              size="compact-xl"
              radius="lg"
              px={32}
              w={256}
            >
              Více služeb
            </Button>
          </Link>
        </Flex>

        <Card
          py="5vh"
          px={32}
          radius={0}
          style={{
            position: "relative",
            width: "100lvw",
            alignItems: "center",
            justifyContent: "center",
            gap: 24,
          }}
          c="white"
          bg="#101c24"
        >
          <Title
            order={3}
            fz={32}
            lh={1}
            style={{ scrollMarginTop: 100 }}
            ta="center"
          >
            Více informací o našich službách?
          </Title>
          <Text fz={20} ta="center">
            Zjistěte více informací o dané službě pro vaše vozidlo.
          </Text>
          <Link
            href="/vozidla"
            style={{ color: "inherit", textDecoration: "inherit" }}
          >
            <Button
              color="#dc1735"
              variant="filled"
              size="compact-xl"
              radius="lg"
              px={32}
            >
              Mám zájem
            </Button>
          </Link>
        </Card>

        <Form />
      </Stack>
      <Footer />
    </>
  );
};

export default Cenik;
