import Footer from "@/components/Footer";
import Form from "@/components/Form";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  AspectRatio,
  Button,
  Card,
  Flex,
  Grid,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import Hero from "@/components/Hero";
import { useMediaQuery } from "@mantine/hooks";
import classes from "../styles/Index.module.css";
import LatestRealizations from "@/components/LatestRealizations";
import { AnimatedSection } from "@/components/AnimatedSection";
import { StaggeredItem, StaggeredItems } from "@/components/StaggeredItems";
import dynamic from "next/dynamic";
import supabase from "@/lib/supabaseClient";

const PromotionalBanner = dynamic(
  () => import("../components/PromotionalBanner"),
  {
    ssr: false,
  }
);

export default function Home({ data }) {
  const smallWindow = useMediaQuery("(max-width: 1200px)");

  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="TTC_WEB_Icon.svg" />
      </Head>
      <Navbar />
      <Hero
        image="/Foty_web_uvodni_hlavni_fotky/Uvod_foto.webp"
        title="Profesionální úpravy řídících jednotek motorů a emisních systémů."
        subText={
          <Flex gap={16} wrap="wrap" justify="center" align="center">
            <Link
              href="/sluzby"
              style={{ color: "inherit", textDecoration: "inherit" }}
            >
              <Button
                color="#e84048"
                variant="filled"
                size="compact-xl"
                radius="md"
                px={32}
              >
                Zjistit více
              </Button>
            </Link>
            <a
              href="tel:+420 602 562 650"
              style={{ color: "inherit", textDecoration: "inherit" }}
            >
              <Button
                color="#e840486f"
                c="#ffF"
                variant="filled"
                size="compact-xl"
                radius="md"
                px={32}
              >
                Zavolejte nám
              </Button>
            </a>
          </Flex>
        }
      />
      <Stack
        px={32}
        py={128}
        justify="center"
        align="center"
        gap={smallWindow ? 64 : 128}
        maw={1280}
        mx="auto"
        w="100%"
      >
        {data.length > 0 && <PromotionalBanner data={data} />}

        <AnimatedSection
          animationType="fadeIn"
          delay={0.2}
          style={{ width: "100%" }}
        >
          <Grid w="100%" gutter={smallWindow ? 24 : 64}>
            <Grid.Col span={{ base: 12, sm: 6 }}>
              <AspectRatio
                ratio={4 / 3}
                style={{
                  position: "relative",
                  borderRadius: 16,
                  boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                }}
                h={smallWindow ? 360 : "100%"}
              >
                <Image
                  quality={100}
                  src="/nove/Fotky_uvodni_stranka/1_foto_text.webp"
                  alt="/nove/Fotky_uvodni_stranka/1_foto_text.webp"
                  fill
                  sizes="100vw"
                  style={{ borderRadius: 16 }}
                />
              </AspectRatio>
            </Grid.Col>
            <Grid.Col span={{ base: 12, sm: 6 }}>
              <Stack
                align="center"
                justify="center"
                w="100%"
                gap={64}
                py={smallWindow ? 0 : 32}
              >
                <Stack gap={16} justify="center" w="100%">
                  <Title
                    order={3}
                    fz={32}
                    lh={1}
                    style={{ scrollMarginTop: 100 }}
                  >
                    Na jaké služby se zaměřujeme?
                  </Title>
                  <Text fz={20} maw={480}>
                    Zaměřujeme se převážně na chiptuning - optimalizace softwaru
                    v řídicích jednotkách motorů, řešení problémů s emisními
                    systémy SCR (AdBlue), DPF a EGR... Dále na diagnostiku
                    vozidel a strojů, řešíme chybová hlášení a kontrolky závad,
                    programování automatických převodovek, opravy elektronických
                    jednotek a mnoho dalšího ...
                  </Text>
                  <Link
                    href="/sluzby"
                    style={{ color: "inherit", textDecoration: "inherit" }}
                  >
                    <Button
                      color="#e84048"
                      variant="filled"
                      size="compact-xl"
                      radius="md"
                      px={32}
                    >
                      Více služeb
                    </Button>
                  </Link>
                </Stack>
              </Stack>
            </Grid.Col>
          </Grid>
        </AnimatedSection>

        <Stack gap={32}>
          <AnimatedSection
            animationType="fadeIn"
            delay={0.2}
            style={{ width: "100%" }}
          >
            <LatestRealizations
              categoryIds={["fe2ecd8c-a425-4ad9-8402-caca529ae690"]}
              title="Nejnovější realizace osobních vozidel"
              subText="Podívejte se na naše nejnovější projekty a přesvědčte se o kvalitě našich služeb"
              showButton={false}
            />
          </AnimatedSection>
          <AnimatedSection
            animationType="fadeIn"
            delay={0.2}
            style={{ width: "100%" }}
          >
            <LatestRealizations
              categoryIds={[
                "3b2aa847-0708-4317-a850-7fbf2a47e653",
                "5cad46f3-5bce-4b40-b65d-9ec2f2547ee3",
                "5dd4eb6c-bb4c-4c63-b290-6a554aefff44",
                "6c86f851-a4b6-4496-b706-139ac6517e78",
                "9ea2c9c3-e82e-40ca-ac22-357a4b198f0d",
                "a2dd1a47-8043-46fe-9091-772b7f08ee56",
                "aa8b5fd2-3493-4d3e-9904-0aea8763b374",
                "b973b975-5b7f-4768-9975-3911fd0c8690",
              ]}
              title="Nejnovější realizace vozidel a techniky"
              subText="Podívejte se na další realizace a přesvědčte se o kvalitě našich služeb"
              showButton={true}
            />
          </AnimatedSection>
        </Stack>

        <AnimatedSection animationType="fadeIn" delay={0.2}>
          <Card
            py="5vh"
            px={32}
            radius={0}
            style={{
              position: "relative",
              width: "100lvw",
              alignItems: "center",
              justifyContent: "center",
              gap: 48,
            }}
            c="white"
            bg="#101c24"
          >
            <Grid w="100%" gutter={smallWindow ? 24 : 64} maw={1280} mx="auto">
              <Grid.Col span={{ base: 12, sm: 6 }}>
                <AspectRatio
                  ratio={4 / 3}
                  style={{
                    position: "relative",
                    borderRadius: 16,
                  }}
                  h={smallWindow ? 360 : "100%"}
                >
                  <Image
                    quality={100}
                    src="/nove/Fotky_uvodni_stranka/2_foto_text.webp"
                    alt="/nove/Fotky_uvodni_stranka/2_foto_text.webp"
                    fill
                    sizes="100vw"
                    style={{ borderRadius: 16 }}
                  />
                </AspectRatio>
              </Grid.Col>
              <Grid.Col span={{ base: 12, sm: 6 }}>
                <Stack align="center" justify="center" w="100%" gap={64}>
                  <Stack gap={16} justify="center" w="100%">
                    <Text fz={20} maw={480}>
                      Našimi zákazníky, jsou převážně majitelé dopravní
                      techniky, zemědělských strojů a osobních aut, kteří chtějí
                      zvýšit výkon, snížit spotřebu pohonných hmot a
                      optimalizovat své provozní náklady za opravy a servis
                      emisních systému (SCR AdBlue, DPF a EGR) a nebo měli
                      problémy po neodborném chiptuningu.
                    </Text>
                    <Text fz={20} maw={480}>
                      Pokud máte i vy zájem, kontaktujte nás na telefonním čísle{" "}
                      <Link
                        href="tel:+420 602 562 650"
                        style={{
                          color: "inherit",
                          whiteSpace: "nowrap",
                        }}
                      >
                        +420 602 562 650
                      </Link>{" "}
                      a nebo vyplňte jednoduchý formulář.
                    </Text>
                    <Link
                      href="#form"
                      style={{ color: "inherit", textDecoration: "inherit" }}
                    >
                      <Button
                        color="#e84048"
                        variant="filled"
                        size="compact-xl"
                        radius="md"
                        px={32}
                      >
                        Kontaktujte nás
                      </Button>
                    </Link>
                  </Stack>
                </Stack>
              </Grid.Col>
            </Grid>
          </Card>
        </AnimatedSection>

        <Stack gap={32} justify="center" w="100%">
          <Title
            order={3}
            fz={32}
            lh={1}
            ta="center"
            style={{ scrollMarginTop: 100 }}
          >
            Hlavní důvody, proč si vybrat právě nás!
          </Title>

          <Flex
            direction={smallWindow ? "column" : "row"}
            w="100%"
            gap={smallWindow ? 24 : 64}
            maw={1280}
            mx="auto"
            align="stretch"
            justify="center"
          >
            <Card
              h={192}
              c="white"
              bg="#101c24"
              radius={16}
              p={32}
              style={{
                boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                justifyContent: "center",
                flex: "1 1 100%",
              }}
            >
              <Stack w="100%" align="center" justify="center">
                <Text fz={20} fw={700} c="white" ta="center">
                  Měření výkonu
                </Text>
                <Text c="white" ta="center">
                  Dokážeme měřit výkon na 4x4 válcové zkušebně výkonu + Agro
                  Dyno měření výkonu.
                </Text>
              </Stack>
            </Card>
            <Card
              h={192}
              c="white"
              bg="#101c24"
              radius={16}
              p={48}
              style={{
                boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                justifyContent: "center",
                flex: "1 1 100%",
              }}
            >
              <Stack w="100%" align="center" justify="center">
                <Text fz={20} fw={700} c="white" ta="center">
                  Bezpečnost
                </Text>
                <Text c="white" ta="center">
                  Děláme pouze kvalitní a bezpečné úpravy.
                </Text>
              </Stack>
            </Card>
            <Card
              h={192}
              c="white"
              bg="#101c24"
              radius={16}
              p={48}
              style={{
                boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                justifyContent: "center",
                flex: "1 1 100%",
              }}
            >
              <Stack w="100%" align="center" justify="center">
                <Text fz={20} fw={700} c="white" ta="center">
                  Garance
                </Text>
                <Text c="white" ta="center">
                  Garantujeme zachování emisních limitů.
                </Text>
              </Stack>
            </Card>
          </Flex>
        </Stack>

        <Stack gap={32} justify="center" w="100%">
          <Title
            order={3}
            fz={32}
            lh={1}
            style={{ scrollMarginTop: 100 }}
            ta="center"
          >
            Na jaké vozidla a techniku se zaměřujeme?
          </Title>
          <StaggeredItems>
            <Grid w="100%" gutter={32} maw={1280} mx="auto">
              <Grid.Col span={{ base: 12, sm: 6 }}>
                <StaggeredItem>
                  <Link
                    href="/sluzby/zkusebna-vykonu"
                    style={{ color: "inherit", textDecoration: "inherit" }}
                  >
                    <AspectRatio ratio={smallWindow ? 1 / 1 : 16 / 9}>
                      <Card
                        className={classes.card}
                        radius={16}
                        style={{
                          boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                          justifyContent: "center",
                        }}
                        p={48}
                      >
                        <Stack align="center" justify="center" h="100%">
                          <Text fz={32} fw={700} ta="center">
                            Dopravní technika
                          </Text>
                          <Stack align="center" justify="center" gap={0}>
                            <Text fz={20} ta="center">
                              osobní vozidla
                            </Text>
                            <Text fz={20} ta="center">
                              nákladní vozy / autobusy
                            </Text>
                            <Text fz={20} ta="center">
                              dodávky / obytné vozy
                            </Text>
                          </Stack>
                        </Stack>
                      </Card>
                    </AspectRatio>
                  </Link>
                </StaggeredItem>
              </Grid.Col>
              <Grid.Col span={{ base: 12, sm: 6 }}>
                <StaggeredItem>
                  <Link
                    href="/sluzby/zemedelska-technika"
                    style={{ color: "inherit", textDecoration: "inherit" }}
                  >
                    <AspectRatio ratio={smallWindow ? 1 / 1 : 16 / 9}>
                      <Card
                        className={classes.card}
                        radius={16}
                        style={{
                          boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                          justifyContent: "center",
                        }}
                        p={48}
                      >
                        <Stack align="center" justify="center" h="100%">
                          <Text fz={32} fw={700} ta="center">
                            Zemědělská technika
                          </Text>
                          <Stack align="center" justify="center" gap={0}>
                            <Text fz={20} c="white" ta="center">
                              -
                            </Text>
                            <Text fz={20} ta="center">
                              traktory / kombajny
                            </Text>
                            <Text fz={20} ta="center">
                              manipulátory / řezačky
                            </Text>
                          </Stack>
                        </Stack>
                      </Card>
                    </AspectRatio>
                  </Link>
                </StaggeredItem>
              </Grid.Col>
              <Grid.Col span={{ base: 12, sm: 6 }}>
                <StaggeredItem>
                  <Link
                    href="/sluzby/stavebni-technika"
                    style={{ color: "inherit", textDecoration: "inherit" }}
                  >
                    <AspectRatio ratio={smallWindow ? 1 / 1 : 16 / 9}>
                      <Card
                        className={classes.card}
                        radius={16}
                        style={{
                          boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                          justifyContent: "center",
                        }}
                        p={48}
                      >
                        <Stack align="center" justify="center" h="100%">
                          <Text fz={32} fw={700} ta="center">
                            Stavební technika
                          </Text>
                          <Stack align="center" justify="center" gap={0}>
                            <Text fz={20} ta="center">
                              bagry / nakladače
                            </Text>
                            <Text fz={20} ta="center">
                              buldozery / traktorbagry
                            </Text>
                            <Text fz={20} ta="center">
                              drtiče
                            </Text>
                          </Stack>
                        </Stack>
                      </Card>
                    </AspectRatio>
                  </Link>
                </StaggeredItem>
              </Grid.Col>
              <Grid.Col span={{ base: 12, sm: 6 }}>
                <StaggeredItem>
                  <Link
                    href="/sluzby/zkusebna-vykonu"
                    style={{ color: "inherit", textDecoration: "inherit" }}
                  >
                    <AspectRatio ratio={smallWindow ? 1 / 1 : 16 / 9}>
                      <Card
                        className={classes.card}
                        radius={16}
                        style={{
                          boxShadow: "rgba(0, 0, 0, 0.25) 0px 5px 15px",
                          justifyContent: "center",
                        }}
                        p={48}
                      >
                        <Stack align="center" justify="center" h="100%">
                          <Text fz={32} fw={700} ta="center">
                            Lesní technika
                          </Text>
                          <Stack align="center" justify="center" gap={0}>
                            <Text fz={20} c="white" ta="center">
                              -
                            </Text>
                            <Text fz={20} ta="center">
                              harvestory / vyvážecí soupravy
                            </Text>
                            <Text fz={20} ta="center">
                              lesní traktory
                            </Text>
                          </Stack>
                        </Stack>
                      </Card>
                    </AspectRatio>
                  </Link>
                </StaggeredItem>
              </Grid.Col>
            </Grid>
          </StaggeredItems>
        </Stack>

        <Form simplified />
      </Stack>
      <Footer />
    </>
  );
}

export const getStaticProps = async () => {
  const now = new Date().toISOString();

  const { data, error } = await supabase
    .from("promotional_banners")
    .select("*")
    .eq("is_active", true)
    .or(`start_date.is.null,start_date.lte.${now}`)
    .or(`end_date.is.null,end_date.gte.${now}`)
    .order("display_order", { ascending: true });

  if (error) {
    console.error("Error fetching promotional banners:", error);
    return {
      props: { data: [] },
      revalidate: 120, // 2 minutes
    };
  }

  return {
    props: { data },
    revalidate: 120, // 2 minutes
  };
};
