import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Link from "next/link";
import styles from "./making.module.css";

const Realizace = () => {
  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="TTC_WEB_Icon.svg" />
      </Head>
      <Navbar />
      <main className={styles.realizace}>
        <div className={styles.hero}>
          <div>
            <h1>PŘIPRAVUJEME</h1>
          </div>
        </div>
        <p className={styles.text}>
          Nastala chyba! Tato stránka se teprve připravuje :(
        </p>
        <p>&#8203;</p>
      </main>
      <Footer />
    </>
  );
};

export default Realizace;
