import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

const StyledRealizace = styled.main`
  width: 100%;
  height: auto;

  color: #101c24;

  .hero {
    margin-bottom: 6rem;
    width: 100vw;
    height: 480px;

    background-image: url("/Foty_web_uvodni_hlavni_fotky/Realizace_foto.webp");
    background-size: cover;
    background-position: center;

    display: flex;
    align-content: center;
    justify-content: center;

    color: white;

    div {
      align-self: center;
      text-align: center;

      h1 {
        font-size: 4rem;
        font-weight: bolder;
        line-height: 4.75rem;

        @media (max-width: 1280px) {
          font-size: 3rem;
        }
        @media (max-width: 600px) {
          font-size: 2rem;
        }
      }
      p {
        font-size: 2rem;
        font-weight: 100;

        @media (max-width: 1280px) {
          font-size: 1.5rem;
          letter-spacing: 0;
        }
        @media (max-width: 600px) {
          font-size: 1.5rem;
        }
      }
    }
  }

  .container {
    width: 75vw;
    margin: 0 auto 3rem auto;
    display: flex;
    flex-direction: row;
    justify-content: center;
    @media (max-width: 1280px) {
      flex-wrap: wrap;
      gap: 3rem;
    }
    gap: 6rem;

    .card {
      box-shadow: 0 1px 1px rgba(0, 0, 0, 0.12), 0 2px 2px rgba(0, 0, 0, 0.12),
        0 4px 4px rgba(0, 0, 0, 0.12), 0 8px 8px rgba(0, 0, 0, 0.12),
        0 16px 16px rgba(0, 0, 0, 0.12);
      width: 18rem;
      height: 8rem;
      padding: 1rem;

      display: flex;
      flex-direction: row-reverse;
      justify-content: center;

      border-radius: 1rem;
      background-color: #101c24;
      color: white;
      text-align: center;
      text-decoration: none;

      p {
        align-self: center;
        text-align: left;
        height: max-content;
        width: min-content;
        border-left: 2px white solid;
        padding-left: 1rem;
        text-decoration: none;
      }

      img {
        height: 6rem;
        width: 6rem;
        object-fit: contain;
        padding-right: 1rem;
      }
      svg {
        height: 6rem;
        width: 6rem;
        padding-right: 1rem;
      }
    }
  }

  p.text {
    font-size: 1.5rem;
    font-weight: 700;
    text-align: center;
    margin-bottom: 4rem;
    max-width: 80vw;
    margin: 6rem auto 4rem auto;

    @media (max-width: 900px) {
      font-size: 1rem;
    }
  }
`;

const Realizace = () => {
  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/media/Premium Package/Logos (Vector Format)/Transparent.svg"
        />
      </Head>
      <Navbar />
      <StyledRealizace>
        <div className="hero">
          <div>
            <h1>REALIZACE</h1>
          </div>
        </div>
        <div className="container">
          <Link href="/making" className="card">
            <p>Zemědělská technika</p>
            <svg
              fill="#fff"
              height="800px"
              width="800px"
              version="1.2"
              baseProfile="tiny"
              id="tractor_by_Adioma"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 256 196"
            >
              <path
                d="M175.9,154.3c0,21.6,17.5,39.1,39.1,39.1s39.1-17.5,39.1-39.1c0-21.6-17.5-39.1-39.1-39.1S175.9,132.7,175.9,154.3z
	 M202.2,154.3c0-7,5.7-12.7,12.7-12.7c7,0,12.7,5.7,12.7,12.7c0,7-5.7,12.7-12.7,12.7C207.9,167,202.2,161.3,202.2,154.3z M2,148
	c0,25,20.3,45.3,45.3,45.3c25,0,45.3-20.3,45.3-45.3s-20.3-45.3-45.3-45.3C22.3,102.7,2,123,2,148z M28.4,148c0-2.7,0.6-5.3,1.6-7.6
	c2.9-6.7,9.6-11.3,17.3-11.3s14.4,4.7,17.3,11.3c1,2.3,1.6,4.9,1.6,7.6c0,10.4-8.5,18.9-18.9,18.9S28.4,158.5,28.4,148z M99.7,140.4
	h70.6c5.9-19,23.7-32.8,44.6-32.8V75.4c0-8.1-6.6-14.7-14.7-14.7h-15.5V16.2h-12.5v44.5h-45.4L105.2,8.3c-1.5-3.3-4.8-5.5-8.4-5.5
	H34.4v57.9L11.8,81.4v27.4c9.4-8.5,21.9-13.7,35.6-13.7C73.9,95.1,96,114.8,99.7,140.4z M47.3,60.7v-45H94l16.2,45H47.3z"
              />
            </svg>
          </Link>
          <Link href="/making" className="card">
            <p>Nákladní vozidla</p>
            <img src="/media/icons/van.png" alt="" />
          </Link>
        </div>
        <div className="container" style={{ marginBottom: "6rem" }}>
          <Link href="/making" className="card">
            <p>Osobní vozidla</p>
            <img src="/media/icons/car.png" alt="" />
          </Link>
          <Link href="/making" className="card">
            <p>Stavební technika</p>
            <img src="/media/icons/const.png" alt="" />
          </Link>
        </div>
        <p>&#8203;</p>
      </StyledRealizace>
      <Footer />
    </>
  );
};

export default Realizace;
