import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

const StyledSluzby = styled.main`
  background-image: url("./bg.svg");
  background-size: cover;
  background-position: top;

  width: 100%;
  height: auto;
  min-height: 100vh;

  color: #101c24;

  .hero {
    margin-bottom: 8rem;
    width: 100vw;
    height: 50vh;

    background-image: url("./media/foto/sluzby.webp");
    background-size: cover;
    background-position: 75%;

    display: flex;
    align-content: center;
    justify-content: center;

    color: white;

    div {
      align-self: center;
      text-align: center;

      h1 {
        font-size: 4rem;
        font-weight: bolder;
        line-height: 4.75rem;

        @media (max-width: 1280px) {
          font-size: 3rem;
        }
        @media (max-width: 600px) {
          font-size: 2rem;
        }
      }
      p {
        font-size: 2rem;
        font-weight: 100;

        @media (max-width: 1280px) {
          font-size: 1.5rem;
          letter-spacing: 0;
        }
        @media (max-width: 600px) {
          font-size: 1.5rem;
        }
      }
    }
  }

  section {
    max-width: 75vw;
    margin: auto;
    display: flex;
    flex-direction: column;

    h2 {
      font-size: 2%.5;
      font-weight: 700;
    }

    &.text {
      gap: 2rem;
      font-size: 1.5rem;
      margin-bottom: 4rem;
      ul {
        padding-left: 1rem;
        list-style-type: "- ";
        display: flex;
        flex-direction: column;
        gap: 2rem;
      }
    }

    &.warn {
      margin-bottom: 4rem;
      text-align: center;
      font-size: 14px;
    }

    &.grid {
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
      margin-bottom: 4rem;
      @media (max-width: 1280px) {
        flex-direction: column;
      }

      & > .card {
        width: calc(50% - 2rem);
        @media (max-width: 1280px) {
          width: calc(100% - 2rem);
        }
        margin: 1rem;
        aspect-ratio: 16/9;
        display: flex;
        flex-direction: column;
        align-items: start;
        justify-content: end;
        padding: 2rem;
        color: white;
        background-size: cover;
        background-position: center;
        position: relative;
        border-radius: 1rem;

        transition: 500ms ease-in-out;
        &:hover {
          transform: scale(1.025);
        }
      }

      & > .card::after {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.5);
        border-radius: 1rem;
      }

      h3,
      p,
      a {
        position: relative;
        z-index: 1;
      }

      h3 {
        font-size: 1.5rem;
        margin-bottom: 0.5rem;
      }

      p {
        font-size: 1.2rem;
        margin-bottom: 1rem;
      }

      a {
        background: crimson;
        color: white;
        padding: 0.5rem 1rem;
        border-radius: 5px;
        text-decoration: none;
        transition: 250ms;

        &:hover {
          background: white;
          color: crimson;
        }
      }
    }
  }
`;

const cardData = [
  {
    heading: "MĚŘENÍ VÝKONU",
    subheading: "Osobní vozidla & Zemědělská technika",
    button: "Více informací",
    link: "/sluzby/zkusebna-vykonu",
    background: "./Fotky_WEBP/TTC_Performance_Ferrari-70 kopie.webp",
  },
  {
    heading: "ZEMĚDĚLSKÁ TECHNIKA",
    subheading: "",
    button: "Více informací",
    link: "/sluzby/zemedelska-technika",
    background: "./Fotky_WEBP/Traktor_AGRO_DYNO_brzda-109 kopie.webp",
  },
  {
    heading: "NÁKLADNÍ VOZIDLA",
    subheading: "",
    button: "Více informací",
    link: "/sluzby/nakladni-vozidla",
    background: "./Fotky_WEBP/IMG_2971 kopie.webp",
  },
  {
    heading: "STAVEBNÍ TECHNIKA",
    subheading: "",
    button: "Více informací",
    link: "/sluzby/stavebni-technika",
    background: "./Fotky_WEBP/IMG_4773 kopie.webp",
  },
  {
    heading: "LESNÍ TECHNIKA",
    subheading: "",
    button: "Více informací",
    link: "/sluzby/lesni-technika",
    background: "./Fotky_WEBP/untitled-2.22.1 kopie.webp",
  },
  {
    heading: "OSOBNÍ VOZIDLA",
    subheading: "",
    button: "Více informací",
    link: "/sluzby/osobni-vozidla",
    background: "./Fotky_WEBP/TTC_Performance_Ferrari-47 kopie.webp",
  },
];

const Sluzby = () => {
  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/media/Premium Package/Logos (Vector Format)/Transparent.svg"
        />
      </Head>
      <Navbar />
      <StyledSluzby>
        <div className="hero">
          <div>
            <h1>NAŠE SLUŽBY</h1>
            <span style={{ color: "crimson", fontSize: 20 }}>
              Na co se specializujeme?
            </span>
          </div>
        </div>
        <section className="text">
          <h2>Nabízíme široký sortiment služeb</h2>
          <p>
            Naše společnost nabízí profesionální softwarové úpravy řídících
            jednotek motorů, emisních systémů a automatických převodovek.
          </p>
          <p>
            Vlastní vývoj softwaru - Veškeré úpravy jsou vyvíjeny a testovány na
            zkušebně výkonu.
          </p>
          <p>
            Kvalitní a bezpečné úpravy, díky spolupráci s nejlepšími na trhu:
            Dimsport, Autotuner, Alientech Bapro, Dynoproject, Remus výfukové
            systémy, DTE systémy a Eventuri karbonové sání a další ..
          </p>
        </section>
        <section className="grid">
          {cardData.map((card, index) => (
            <div
              key={index}
              className="card"
              style={{ backgroundImage: `url("${card.background}")` }}
            >
              <h3>{card.heading}</h3>
              {card.subheading && (
                <p style={{ borderLeft: "1px solid white", paddingLeft: 4 }}>
                  {card.subheading}
                </p>
              )}
              <Link href={card.link}>{card.button}</Link>
            </div>
          ))}
        </section>
        <section className="text">
          <h2>Záruka na naše služby</h2>
          <ul>
            <li>Záruka 14 dní na vrácení peněz.</li>
            <li>
              Záruka 12 měsíců na řídící jednotku. <br />
              (V případě mechanického zásahu do řídící jednotky).
            </li>
            <li>Záruka 10 let na námi upravený software</li>
          </ul>
        </section>
        <section className="warn">
          <p>
            <p>
              Dle novely zákona č. 56/2001 Sb. o podmínkách provozu na pozemních
              komunikacích se vozidlo s neschválenou úpravou stává nezpůsobilé k
              provozu na pozemních komunikacích. Novela zákona, §83 odstavec 1,
              písmeno i) definuje podmínky takto: "fyzická osoba se dopustí
              přestupku tím, že jako provozovatel silničního vozidla v rozporu s
              §38 odst. 1 písm. a) provozuje na pozemních komunikacích vozidlo,
              které je technicky nezpůsobilé k provozu."
            </p>
          </p>
        </section>
      </StyledSluzby>
      <Footer />
    </>
  );
};

export default Sluzby;
