import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import styled from "styled-components";

const StyledCenik = styled.main`
  background-image: url("./bg.svg");
  background-size: cover;
  background-position: top;

  width: 100%;
  height: auto;
  min-height: 100vh;

  color: #101c24;

  h1 {
    font-size: 5rem;
    letter-spacing: -4px;
    font-weight: 900;
    text-align: center;
    margin: 8rem 0;

    @media (max-width: 1280px) {
      font-size: 4rem;
    }
    @media (max-width: 600px) {
      font-size: 3rem;
    }
  }

  section {
    height: auto;
    width: 75vw;
    margin: auto;
    padding: 5vw 12.5vw;
    margin-bottom: 8rem;

    border-radius: 2rem;
    background-color: #101c24;
    color: white;

    display: flex;
    flex-direction: column;
    gap: 4rem;

    -webkit-box-shadow: 48px 32px 0px 0px rgba(200, 196, 204, 1);
    -moz-box-shadow: 48px 32px 0px 0px rgba(200, 196, 204, 1);
    box-shadow: 48px 32px 0px 0px rgba(200, 196, 204, 1);

    &.reverse {
      -webkit-box-shadow: -48px 32px 0px 0px rgba(200, 196, 204, 1);
      -moz-box-shadow: -48px 32px 0px 0px rgba(200, 196, 204, 1);
      box-shadow: -48px 32px 0px 0px rgba(200, 196, 204, 1);
    }

    h2 {
      font-size: 3.5rem;
      letter-spacing: -4px;
      font-weight: 900;
      text-align: center;

      @media (max-width: 1280px) {
        font-size: 2rem !important;
        letter-spacing: 0px;
      }
      @media (max-width: 600px) {
        font-size: 1.5rem !important;
      }
    }

    ul li {
      font-size: 2rem;
      margin: 1.5rem 0;
      font-weight: 400;

      @media (max-width: 1280px) {
        font-size: 1.5rem !important;
        letter-spacing: 0px;
      }
      @media (max-width: 600px) {
        font-size: 1rem !important;
      }

      span {
        font-weight: 600;
      }
    }

    p {
      font-size: 3rem;
      font-weight: 400;
      text-align: center;

      @media (max-width: 1280px) {
        font-size: 2rem !important;
        letter-spacing: 0px;
      }
      @media (max-width: 600px) {
        font-size: 1.25rem !important;
      }

      span {
        font-weight: 600;
      }
    }
  }
`;

const Cenik = () => {
  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/media/Premium Package/Logos (Vector Format)/Transparent.svg"
        />
      </Head>
      <Navbar />
      <StyledCenik>
        <img src="./media/foto/cenik.png" alt="" />
        <h1>Náš ceník</h1>
        <section>
          <h2>Optimalizace výkonu</h2>
          <ul>
            <li>
              nákladní automobily obsah motoru do 7 000 ccm{" "}
              <span>- 15 200 Kč</span>
            </li>
            <li>
              nákladní automobily obsah motoru nad 7 000 ccm{" "}
              <span>- 20 200 Kč</span>
            </li>
            <li>
              zemědělské stroje <span>- 20 200 Kč</span>
            </li>
            <li>
              stavební stroje <span>- od 23 200 Kč</span> (dle systému)
            </li>
            <li>
              osobní automobily <span>- od 3 500 Kč</span> (dle systému)
            </li>
          </ul>
        </section>
        <section className="reverse">
          <h2>Deaktivace SCR (AdBlue) / DPF</h2>
          <ul>
            <li>
              nákladní automobily <span>- 22 200 Kč</span>
            </li>
            <li>
              zemědělské stroje <span>- 22 200 Kč</span>
            </li>
            <li>
              stavební stroje <span>- od 25 200 Kč </span> (dle systému)
            </li>
          </ul>
          <p>
            Deaktivace EGR <span>- 18 200 Kč</span>
          </p>
          <p>
            Vypnutí chybových kódů DTC <span>- od 8000 Kč</span>
          </p>
          <p>
            Plnění klimatizace <span>- od 400 Kč</span>
          </p>
        </section>
        <section>
          <h2>Diagnostika</h2>
          <ul>
            <li>
              osobní automobily <span>- 400 Kč</span>
            </li>
            <li>
              nákladní automobily <span>- 1 200 Kč</span>
            </li>
            <li>
              stavební stroje <span>- od 25 200 Kč </span> (dle systému)
            </li>
          </ul>
          <p>
            Další úpravy <span>- dle dohody</span>
          </p>
        </section>
        <p>&#8203;</p>
      </StyledCenik>
      <Footer />
    </>
  );
};

export default Cenik;
