import Navbar from "@/components/Navbar";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

const Main = styled.main`
  width: 100%;
  height: auto;
  min-height: 100vh;

  background-image: url("./media/texture.png");
  background-size: cover;
  background-position: top;

  .hero {
    width: 100vw;
    height: 100vh;

    background-image: url("./media/foto/jay-huang-aeouwx28n6M-unsplash.jpg");
    background-size: cover;
    background-position: center;

    display: flex;
    align-content: center;
    justify-content: center;

    color: white;

    div {
      align-self: center;
      text-align: center;

      h1 {
        font-size: 6rem;
        font-weight: bolder;
        line-height: 4.75rem;
      }
      p {
        font-size: 4rem;
        font-weight: 100;
        letter-spacing: 0.25rem;
      }
    }
  }

  .marks {
    width: 100%;
    height: auto;
    position: relative;
    bottom: 6rem;

    display: flex;
    flex-direction: row;
    justify-content: center;
    gap: 7.5%;

    color: #fff;

    .mark {
      width: 12rem;
      height: 13rem;
      background-color: #101c24cc;
      border: solid 1px gray;
      border-radius: 1rem;

      display: flex;
      flex-direction: column;

      p {
        padding: 2rem 0 1rem 0;
        font-size: 2rem;
        text-align: center;
        height: 6rem;
      }
      img {
        padding: 0.5rem 1rem 0;
        font-size: 2rem;
        text-align: center;
        height: 6rem;
      }
    }
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/media/Premium Package/Logos (Vector Format)/Transparent.svg"
        />
      </Head>
      <Navbar />
      <Main>
        <div className="hero">
          <div>
            <h1>TTC Performance</h1>
            <p>profesionální chiptuning</p>
          </div>
        </div>
        <div className="marks">
          <div className="mark">
            <p>Kvalita!</p>
            <img src="./media/icons/iconmonstr-award-7.svg" />
          </div>
          <div className="mark">
            <p>Rychlost!</p>
            <img src="./media/icons/iconmonstr-time-19.svg" />
          </div>
          <div className="mark">
            <p>Záruka!</p>
            <img src="./media/icons/iconmonstr-certificate-12.svg" />
          </div>
        </div>
      </Main>
    </>
  );
}
