import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import styled from "styled-components";

const StyledSluzby = styled.main`
  background-image: url("./bg.svg");
  background-size: cover;
  background-position: top;

  width: 100%;
  height: auto;
  min-height: 100vh;

  color: #101c24;

  .hero {
    margin-bottom: 8rem;
    width: 100vw;
    height: 50vh;

    background-image: url("./media/foto/sluzby.webp");
    background-size: cover;
    background-position: 75%;

    display: flex;
    align-content: center;
    justify-content: center;

    color: white;

    div {
      align-self: center;
      text-align: center;

      h1 {
        font-size: 4rem;
        font-weight: bolder;
        line-height: 4.75rem;

        @media (max-width: 1280px) {
          font-size: 3rem;
        }
        @media (max-width: 600px) {
          font-size: 2rem;
        }
      }
      p {
        font-size: 2rem;
        font-weight: 100;

        @media (max-width: 1280px) {
          font-size: 1.5rem;
          letter-spacing: 0;
        }
        @media (max-width: 600px) {
          font-size: 1.5rem;
        }
      }
    }
  }

  section {
    width: 100%;
    max-width: 75vw;
    margin: auto;
    margin-bottom: 4rem;
    height: auto;

    display: flex;
    flex-direction: row;
    justify-content: center;
    gap: 1rem;
    @media (max-width: 1280px) {
      flex-direction: column;
      margin-bottom: 4rem;
      img {
        margin: auto !important;
      }
    }

    &.reverse {
      flex-direction: row-reverse;
      @media (max-width: 1280px) {
        flex-direction: column;
        margin-bottom: 4rem;
        img {
          margin: auto !important;
        }
      }

      padding: 2rem 0;

      h2 {
        font-size: 4.5rem !important;
      }

      img {
        margin-left: 0 !important;

        margin-right: auto;

        -webkit-box-shadow: -48px 48px 0px 0px #c3c7ca7a !important;
        -moz-box-shadow: -48px 48px 0px 0px #c3c7ca7a !important;
        box-shadow: -48px 48px 0px 0px #c3c7ca7a !important;
      }
    }

    .text {
      width: auto;
      display: flex;
      flex-direction: column;
      align-self: center;

      gap: 1rem;

      h2 {
        font-size: 5rem;
        letter-spacing: -4px;
        font-weight: 900;
        text-align: left;
      }

      ul li {
        font-size: 1rem;
        margin: 1.5rem 0;
        font-weight: 700;

        @media (max-width: 1280px) {
          margin: 0.5rem 0;
          font-size: 1rem;
        }

        span {
          font-weight: 300;
        }
      }
    }

    .image {
      max-width: 30vw;
      width: 100%;
      height: 100%;
      max-height: 40vh;
      align-self: center;

      @media (max-width: 900px) {
        max-width: 70vw;
        width: 100%;
        height: 100%;
        max-height: 70vh;
      }

      img {
        max-width: 30vw;
        width: 100%;
        height: 100%;
        max-height: 40vh;
        object-fit: cover;
        border-radius: 1.5rem;

        @media (max-width: 1280px) {
          margin-left: auto !important;
          margin: auto !important;
        }

        @media (max-width: 900px) {
          margin-top: 2rem !important;
          -webkit-box-shadow: 16px 16px 0px 0px #c3c7ca7a !important;
          -moz-box-shadow: 16px 16px 0px 0px #c3c7ca7a !important;
          box-shadow: 16px 16px 0px 0px #c3c7ca7a !important;
        }

        @media (max-width: 900px) {
          max-width: 70vw;
          width: 100%;
          height: 100%;
          max-height: 70vh;
        }

        -webkit-box-shadow: 48px 48px 0px 0px #c3c7ca7a;
        -moz-box-shadow: 48px 48px 0px 0px #c3c7ca7a;
        box-shadow: 48px 48px 0px 0px #c3c7ca7a;
      }
    }
  }

  .final {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    text-align: center;
    font-size: 1rem;

    font-weight: 700;
    max-width: 80vw;
    margin: auto;
    margin-bottom: 2rem;

    h2 {
      padding-bottom: 1rem;
      font-size: 2.5rem;

      @media (max-width: 600px) {
        font-size: 1.5rem !important;
      }
    }
  }

  .end-text {
    margin: auto;
    display: flex;
    flex-direction: column;
    max-width: 70vw;
    gap: 4rem;
    padding: 4rem !important;
    @media (max-width: 900px) {
      padding: 1rem !important;
    }

    p {
      font-size: 0.75rem;
      max-width: 700px;
      margin: auto;
      margin-bottom: 2rem;

      text-align: center;
      @media (max-width: 1280px) {
        text-align: center;
        font-size: 0.75rem;
      }
    }
  }
`;

const Sluzby = () => {
  return (
    <>
      <Head>
        <title>TTC Performance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/media/Premium Package/Logos (Vector Format)/Transparent.svg"
        />
      </Head>
      <Navbar />
      <StyledSluzby>
        <div className="hero">
          <div>
            <h1>NAŠE SLUŽBY</h1>
          </div>
        </div>
        <section>
          <div className="text">
            <ul>
              <li>OPTIMALIZACE VÝKONU SNÍŽENÍ SPOTŘEBY</li>
              <li>DEAKTIVACE SCR (AdBlue)</li>
              <li>DEAKTIVACE DPF</li>
              <li>
                MOBILNÍ CHIPTUNING
                <br />
                <span>(Truck, Agro, Harvest, Construct)</span>
              </li>
            </ul>
          </div>
          <div className="image">
            <img src="./media/IMG_2207-min (1).png" alt="" />
          </div>
        </section>
        <section className="reverse">
          <div className="text">
            <ul>
              <li>SOFTWAROVÉ ÚPRAVY AUTOMATICKÝCH PŘEVODOVEK</li>
              <li>
                SOFTWAROVÉ ÚPRAVY
                <br />
                <span>
                  EGR, START/STOP, DTC, LAMBDA, POPCORN,
                  <br /> LAUNCH CONTROL, VÍŘIVÉ KLAPKY, V-MAX OFF
                </span>
              </li>
              <li>
                DIAGNOSTIKA - <br />
                <span>
                  osobní a nákladní vozidla, zemědělské a stavební stroje
                </span>
              </li>
              <li>SERVIS KLIMATIZACÍ A DEZINFEKCE OZONEM</li>
            </ul>
          </div>
          <div className="image">
            <img src="./media/IMG_8754 (1).png" alt="" />
          </div>
        </section>
        <div className="final">
          <h2 style={{ fontWeight: 900 }}>ZÁRUKA NA NAŠE SLUŽBY</h2>
          <p>Záruka 14 dní na vrácení peněz.</p>
          <p>
            Záruka 12 měsíců na řídící jednotku. (V případě mechanického zásahu
            do řídící jednotky).
          </p>
          <p>Záruka 10 let na námi upravený software.</p>
        </div>
        <div className="end-text">
          <p>
            Dle novely zákona č. 56/2001 Sb. o podmínkách provozu na pozemních
            komunikacích se vozidlo s neschválenou úpravou stává nezpůsobilé k
            provozu na pozemních komunikacích. Novela zákona, §83 odstavec 1,
            písmeno i) definuje podmínky takto: &quot;fyzická osoba se dopustí
            přestupku tím, že jako provozovatel silničního vozidla v rozporu s
            §38 odst. 1 písm. a) provozuje na pozemních komunikacích vozidlo,
            které je technicky nezpůsobilé k provozu.&quot;
          </p>
        </div>
      </StyledSluzby>
      <Footer />
    </>
  );
};

export default Sluzby;
